/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MenuLink {
        "active": boolean;
        "href": string;
        "target": string;
    }
}
declare global {
    interface HTMLMenuLinkElement extends Components.MenuLink, HTMLStencilElement {
    }
    var HTMLMenuLinkElement: {
        prototype: HTMLMenuLinkElement;
        new (): HTMLMenuLinkElement;
    };
    interface HTMLElementTagNameMap {
        "menu-link": HTMLMenuLinkElement;
    }
}
declare namespace LocalJSX {
    interface MenuLink {
        "active"?: boolean;
        "href"?: string;
        "target"?: string;
    }
    interface IntrinsicElements {
        "menu-link": MenuLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "menu-link": LocalJSX.MenuLink & JSXBase.HTMLAttributes<HTMLMenuLinkElement>;
        }
    }
}
